### ISSUE TITLE
CS

### ISSUE THREAD

**Issue by GrahamCampbell** [TimexStudio/CodeIgniter-3.0.0-ORM-Twig#1]
Hi there. Do you actually intend to apply the StyleCI diff? Just asking, because they're quite large, and take a lot of time to generate, relatively speaking.

**Comment by zhiephie** [comment]
Hi Graham, No. I want to try styleCI, but less understanding styleCI, maybe I'll try to use travisCI. I hope you will contribute in this repository

**Comment by GrahamCampbell** [comment]
If you're not intending to ever fix your CS, then I recommend you disable StyleCI as it's a waste of time unless you fix the issues.

**Comment by GrahamCampbell** [comment]
StyleCI can send you a PR with the fixes if you're intested.

**Comment by zhiephie** [comment]
Yeah, I know @GrahamCampbell added StyleCI done https://github.com/TimexStudio/CodeIgniter-3.0.0-ORM-Twig/commit/3a377dee75f3ce49b75c80320be019229652a1e4

**Comment by zhiephie** [comment]
The provided fixer 'ordered_use' cannot be enabled again because it was already enabled by your preset.

how to fix @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
Don't try to disable it when it wasn't enabled. :)

**Comment by GrahamCampbell** [comment]
The error message says it all doesn';t it?

**Comment by GrahamCampbell** [comment]
It was already enabled, so don't enable it again.

**Comment by zhiephie** [comment]
oh okey, thanks
