### ISSUE TITLE
How to use Twig

### ISSUE THREAD

**Issue by PrestonDocks** [TimexStudio/CodeIgniter-3.0.0-ORM-Twig#4]
There is a lot of information on how to use the ORM and it is very good thank you, but as an example I don't know how to parse a twig template and pass the result in  $data['content'] to the view.

Please can you provide an example.

Many Thanks

**Comment by zhiephie** [comment]
This example controller and view : 

[Controller](https://github.com/TimexStudio/CodeIgniter-3.0.0-ORM-Twig/blob/master/application/controllers/Welcome.php#L33-L45)

[View](https://github.com/TimexStudio/CodeIgniter-3.0.0-ORM-Twig/blob/master/application/views/index.php#L9-L11)

your data in controller ``$data['content'] `` parse into twig 
```
{{!content!}}
	<h3>{{!your field!}}</h3>
{{!/content!}}
```
more documentation [Twig](http://twig.sensiolabs.org/)
