### ISSUE TITLE
Filter out by attribute in a related entity.

### ISSUE THREAD

**Issue by agvago** [TimexStudio/CodeIgniter-3.0.0-ORM-Twig#5]
Hi,

I just wondering (maybe exists and I can see it in the doc). Is there a way to filter out by an attribute in a entity related to the main one? e.g. Articles and Comments. I want to do something like **_Articles->Comments->where('title','Hello world')->get()_**. So this should return the articles where the tittle of the comment says "Hellow world".-

Thanks!!

**Comment by zhiephie** [comment]
You can create in model Articles like 

```
class Articles extends Elegant\Model {
  protected $table = "article";

  function comments()
  {
    return $this->belongsToMany('Comments');
  }
}
```
Controller
```
$comments = $article->comments()->where('title', 'Hello World')->get();
foreach($comments as $comment)
{
  echo $comment->title;
}
```
[reff](https://github.com/TimexStudio/CodeIgniter-3.0.0-ORM-Twig#working-with-related-models-record)
