### ISSUE TITLE
unable to find file vender/autoload.php in whoops.php library file

### ISSUE THREAD

**Issue by thesaagar** [TimexStudio/CodeIgniter-3.0.0-ORM-Twig#6]
A PHP Error was encountered
Severity: Warning

Message: require_once(C:\xampp\htdocs\exitosys\ci_orm\application\libraries/../../vendor/autoload.php): failed to open stream: No such file or directory

Filename: libraries/Whoops.php

Line Number: 18

Backtrace:

File: C:\xampp\htdocs\exitosys\ci_orm\application\libraries\Whoops.php
Line: 18
Function: _error_handler

File: C:\xampp\htdocs\exitosys\ci_orm\application\libraries\Whoops.php
Line: 18
Function: __construct

File: C:\xampp\htdocs\exitosys\ci_orm\index.php
Line: 292
Function: require_once

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\exitosys\ci_orm\application\libraries/../../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\exitosys\ci_orm\application\libraries\Whoops.php on line 18
A PHP Error was encountered
Severity: Compile Error

Message: require_once(): Failed opening required 'C:\xampp\htdocs\exitosys\ci_orm\application\libraries/../../vendor/autoload.php' (include_path='C:\xampp\php\PEAR')

Filename: libraries/Whoops.php

Line Number: 18

Backtrace:

**Comment by zhiephie** [comment]
Don't forget run this command ```composer install```

**Comment by thesaagar** [comment]
It worked, thanks
